name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2
      - name: Install golang
        run: sudo apt-get update && sudo apt-get install -y make golang-1.16
      - name: Build
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            filetransfer.linux
            filetransfer.macos
            filetransfer.exe
            LICENSE.txt
